# Generated by Django 4.1.5 on 2023-01-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('anons', models.CharField(max_length=250)),
                ('full_text', models.TextField(blank='True')),
            ],
        ),
    ]
