# Generated by Django 4.1.5 on 2023-01-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='anons',
            new_name='anons_1',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='full_text',
            new_name='full_text_1',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_1',
        ),
    ]
