# Generated by Django 4.1.5 on 2023-01-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_text',
            field=models.TextField(blank='True'),
        ),
    ]
