# Generated by Django 4.1.5 on 2023-01-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_full_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Test',
        ),
    ]
